### ISSUE TITLE
wurfl download fails behind a firewall/proxy

### ISSUE THREAD

**Issue by commuterjoy** [bbc/spassky#10]
From a fresh gem install :
- start the spassky server
- try to connect a device to /device/connect
- the rack log shows a 'Downloading WURFL database' message
- after a few seconds, Errno::ENETUNREACH - Network is unreachable - connect(2):

I'm guessing this is a proxy server problem.

I assume Spassky should work from behind a firewall. IMHO, as long as devices are on the same network (private or otherwise) it shouldn't matter.

**Comment by AndrewVos** [comment]
Yep definitely a proxy issue. RestClient doesn't respect $http_proxy environment variables so we have to set them manually.

Changing this issue to a feature.
