### ISSUE TITLE
Starting the server without a --port throws uninitialized constant error

### ISSUE THREAD

**Issue by commuterjoy** [bbc/spassky#9]
I'm note sure what the expected behaviour is here. Either we have a default port or the README instructions are incorrect.

```
mattc:Spassky chadbm01$ spassky-server 
/Users/chadbm01/.rvm/gems/ruby-1.8.7-p302/gems/spassky-0.1.32/bin/spassky-server:11: uninitialized constant PORT (NameError)
    from /Users/chadbm01/.rvm/gems/ruby-1.8.7-p302/bin/spassky-server:19:in `load'
    from /Users/chadbm01/.rvm/gems/ruby-1.8.7-p302/bin/spassky-server:19
```

**Comment by AndrewVos** [comment]
Yup I added a new --port argument. I'm reworking the code now to use commander though and I'll update the readme when it's working.

https://github.com/visionmedia/commander
